name: Actions Workflows

on: [push]

Jobs:
 run-github-actions:
   runs-on: ubuntu-lastest
   steps:
     - name: Simples JS Actions
       id: greet
       uses: actions/hello-world-javascript-action@v1
       with:
         who-to-greet: John
     - name: Log Greeting Time
       run: echo "${{ steps.greet.outputs.time }}"